### ISSUE TITLE
SCOREBOARD TODO

### ISSUE THREAD

**Issue by TheCrossBoy** [meepen/tttrw#44]
- [x] Only be as tall as needed, currently just set
- [x] Implement system of bodies being IDed/UnIDed
- [x] Show player roles when they die
- [x] Automatically update scoreboard when it should be
